### PR TITLE
feature: Subscription plans inside the UT3ParkingDemo simulation

### PR DESCRIPTION
**Pull request by florian-corby**
Hi Mohammad! 

I am done working on the subscription plan feature (ie. a client, identified by his/her car has a subscription plan ID and we search this ID in the subscription plan table in order to get the reduction for his/her fees).

Could you please review this code and tell me if you detect any bugs or code smells?

Thanks a lot!

### CODE REVIEW

**Comment by MohammadElSakka** [comment]
Bug detected: incorrect percentage for discount rates 
image

Enhancement idea: change "NoPlan" to "Default" for better reporting :)

**Comment by florian-corby** [comment]
Ah oui effectivement. Ça marchait chez moi mais je pense que c'est parce que je n'avais pas refresh la BD dans mes derniers tests. Je vais corriger ça, merci !

**Comment by MohammadElSakka** [comment]
image

Problem still persistent for the % and payment

**Comment by florian-corby** [comment]
Try to delete the parking_demo folder and relaunch the app. Tell me if the problem is still there :)

**Comment by MohammadElSakka** [comment]
works like a charm! I'll continue reviewing

**Pull request merged**
